version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    networks:
      - challenge2-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - challenge2-network

networks:
  challenge2-network: